server:
  port: 8080

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: auth-service

jwt:
  secret: myVerySecretKeyChangeMe
  expiration: 3600000  
